env:
  es6: true
  browser: true
  commonjs: true
  node: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ['react']

overrides:
  - files: ['**/*.tsx']
    rules:
      'react/prop-types': 'off'

settings:
  react:
    version: '16'
